#server:
#  port: 8080
#
#spring:
#  datasource:
#    url: jdbc:mysql://${DB_HOST:localhost}:3306/product_service
#    username: root
#    password: root
#    driverClassName: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
#    hibernate:
#      ddl-auto: update
#  application:
#    name: PRODUCT-SERVICE



spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_service
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080

#the below swagger config is not needed
springdoc:
  api-docs:
    groups:
      enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html